import { Badge, Button, Card, Field, Input, MessageBar, MessageBarBody, Text, Title1, Title2 } from '@fluentui/react-components';
import { useEffect, useState } from 'react';
import type { WalletTransaction } from '../api/types';
import { formatCurrencyAmount } from '../api/money';

function formatDate(value: string) { return new Date(value).toLocaleString(); }
type AdminTransactionStatusFilter = 'PENDING' | 'APPROVED' | 'REJECTED' | 'ALL';
function statusColor(status: string) { return status === 'PENDING' ? 'warning' : ['APPROVED', 'AWAITING_PAYOUT', 'PROCESSING', 'SUCCESS'].includes(status) ? 'success' : ['REJECTED', 'FAILED', 'CANCELLED'].includes(status) ? 'danger' : 'informative'; }
function statusLabel(status: string) { return ['APPROVED', 'AWAITING_PAYOUT', 'PROCESSING', 'SUCCESS'].includes(status) ? 'APPROVED' : status; }

export function AdminTransactionsPage({ sessionAdmin = false, typeFilter, statusFilter = 'PENDING' }: { sessionAdmin?: boolean; typeFilter?: 'DEPOSIT' | 'WITHDRAWAL'; statusFilter?: AdminTransactionStatusFilter }) {
  const [token, setToken] = useState('');
  const [transactions, setTransactions] = useState<WalletTransaction[]>([]);
  const [message, setMessage] = useState('');
  const [rejecting, setRejecting] = useState<WalletTransaction | null>(null);
  const [reason, setReason] = useState('');
  const [proofs, setProofs] = useState<Record<string, string>>({});
  const authHeaders = () => ({ ...(token ? { 'x-admin-token': token } : {}) });
  const load = async () => { const response = await fetch('/api/admin/transactions', { headers: authHeaders() }); const body = await response.json(); if (!response.ok) { setMessage(body.error ?? 'Admin request failed.'); return; } setTransactions(body.transactions); setMessage(''); };
  const loadProof = async (transactionId: string) => { if (proofs[transactionId]) return; const response = await fetch(`/api/admin/transactions/${transactionId}/proof`, { headers: authHeaders() }); const body = await response.json(); if (!response.ok) { setMessage(body.error ?? 'Payment screenshot could not be loaded.'); return; } setProofs((current) => ({ ...current, [transactionId]: body.screenshotData })); };
  const review = async (transaction: WalletTransaction, action: 'approve' | 'reject', rejectionReason?: string) => { const response = await fetch(`/api/admin/transactions/${transaction.id}/${action}`, { method: 'POST', headers: { 'Content-Type': 'application/json', ...authHeaders() }, body: JSON.stringify({ reason: rejectionReason }) }); const body = await response.json(); if (!response.ok) { setMessage(body.error ?? 'Admin action failed.'); return; } setRejecting(null); setReason(''); await load(); };
  const matchesStatus = (transaction: WalletTransaction) => {
    if (statusFilter === 'ALL') return true;
    if (statusFilter === 'PENDING') return transaction.status === 'PENDING';
    if (statusFilter === 'APPROVED') return ['APPROVED', 'AWAITING_PAYOUT', 'PROCESSING', 'SUCCESS'].includes(transaction.status);
    return ['REJECTED', 'FAILED', 'CANCELLED'].includes(transaction.status);
  };
  const visibleDeposits = typeFilter === 'WITHDRAWAL' ? [] : transactions.filter((transaction) => transaction.type === 'DEPOSIT' && matchesStatus(transaction));
  const visibleWithdrawals = typeFilter === 'DEPOSIT' ? [] : transactions.filter((transaction) => transaction.type === 'WITHDRAWAL' && matchesStatus(transaction));
  const renderRow = (transaction: WalletTransaction) => { const currencyCode = transaction.currencyCode ?? 'RWF'; return <Card className="admin-transaction-row" key={transaction.id}><div className="admin-transaction-row__main"><strong>{transaction.type === 'DEPOSIT' ? `${transaction.userName || 'User'} · ${formatCurrencyAmount(transaction.displayAmount ?? transaction.amount, currencyCode)}` : `${transaction.senderName || transaction.receiverName || 'Account holder'} · ${formatCurrencyAmount(transaction.displayAmount ?? transaction.amount, currencyCode)}`}</strong><Text className="muted">{transaction.type === 'DEPOSIT' ? `Payment method: ${transaction.depositMethodName || transaction.paymentMethod} · Payer: ${transaction.senderName} · Phone: ${transaction.phoneNumber}` : `${transaction.phoneNumber} · ${transaction.paymentMethod}`} · {transaction.internalReference}</Text><Text className="muted">{formatDate(transaction.createdAt)}</Text>{transaction.type === 'WITHDRAWAL' && <Text className="admin-transaction-deduction">Deducted fee: {formatCurrencyAmount(transaction.displayFee ?? transaction.withdrawalFee, currencyCode)} · User received: {formatCurrencyAmount(transaction.displayAmountReceived ?? transaction.amountReceived, currencyCode)}</Text>}{transaction.type === 'DEPOSIT' && <details className="admin-deposit-proof" onToggle={(event) => { if (event.currentTarget.open) void loadProof(transaction.id); }}><summary>View payment screenshot</summary>{proofs[transaction.id] ? <a href={proofs[transaction.id]} target="_blank" rel="noreferrer"><img src={proofs[transaction.id]} alt={`Payment proof for ${transaction.internalReference}`} /></a> : <Text className="muted">Loading screenshot...</Text>}</details>}</div><Badge color={statusColor(transaction.status)}>{statusLabel(transaction.status)}</Badge>{transaction.status === 'PENDING' && <div className="admin-transaction-row__actions"><Button appearance="primary" onClick={() => review(transaction, 'approve')}>Approve</Button><Button appearance="secondary" onClick={() => setRejecting(transaction)}>Reject</Button></div>}</Card>; };
  useEffect(() => { if (sessionAdmin) void load(); }, [sessionAdmin]);
  return <div className="page-stack admin-transactions-page">{!sessionAdmin && <><div className="page-intro"><Text className="hero-eyebrow">Admin only</Text><Title1>Transactions review</Title1><Text className="muted">Approve or reject pending deposits and withdrawals. Real payouts require a connected provider.</Text><a className="admin-page-link" href="/admin/settings">Manage deposit payment methods</a></div><Card className="admin-auth-card"><Field label="Admin API token"><Input type="password" value={token} onChange={(_: unknown, data: { value: string }) => setToken(data.value)} placeholder="Enter admin token" /></Field><Button appearance="primary" onClick={load}>Load transactions</Button></Card></>}{sessionAdmin && <div className="admin-section-heading"><div><Text className="home-kicker">Transaction queue</Text><Title2>{typeFilter === 'DEPOSIT' ? 'Deposits' : typeFilter === 'WITHDRAWAL' ? 'Withdrawals' : 'Pending transactions'}</Title2></div><Button appearance="secondary" onClick={() => void load()}>Refresh</Button></div>}{message && <MessageBar intent="error"><MessageBarBody>{message}</MessageBarBody></MessageBar>}{visibleDeposits.length > 0 || typeFilter !== 'WITHDRAWAL' ? <section><Title2>Pending deposits</Title2><div className="admin-transaction-list">{visibleDeposits.length ? visibleDeposits.map(renderRow) : <Text className="muted">No pending deposits.</Text>}</div></section> : null}{visibleWithdrawals.length > 0 || typeFilter !== 'DEPOSIT' ? <section><Title2>Pending withdrawals</Title2><div className="admin-transaction-list">{visibleWithdrawals.length ? visibleWithdrawals.map(renderRow) : <Text className="muted">No pending withdrawals.</Text>}</div></section> : null}{rejecting && <div className="withdrawal-modal__backdrop"><section className="withdrawal-modal" role="dialog" aria-modal="true" aria-labelledby="rejection-title"><h2 id="rejection-title">Rejection Reason</h2><Field label="Reason"><Input value={reason} onChange={(_: unknown, data: { value: string }) => setReason(data.value)} placeholder="Enter rejection reason" /></Field><div className="withdrawal-modal__actions"><Button appearance="secondary" onClick={() => { setRejecting(null); setReason(''); }}>Cancel</Button><Button appearance="primary" disabled={!reason.trim()} onClick={() => review(rejecting, 'reject', reason.trim())}>Reject Transaction</Button></div></section></div>}</div>;
}
