import { Badge, Button, Card, MessageBar, MessageBarBody, Table, TableBody, TableCell, TableHeader, TableHeaderCell, TableRow, Text, Title1, Title2 } from '@fluentui/react-components';
import { ArrowRightRegular, PeopleRegular } from '@fluentui/react-icons';
import type { DashboardData } from '../api/types';

export function InvitePage({ data, state, onRetry }: { data: DashboardData | null; state: string; onRetry: () => void }) {
  if (state === 'loading') return <Card className="state-panel"><Text>Loading referral progress...</Text></Card>;
  if (state === 'error') return <MessageBar intent="error"><MessageBarBody>Referral data could not be loaded. <Button appearance="transparent" onClick={onRetry}>Retry loading referrals</Button></MessageBarBody></MessageBar>;
  if (state === 'empty' || !data) return <Card className="state-panel"><Text className="state-icon">◌</Text><Title2>No referrals yet</Title2><Button appearance="primary" icon={<PeopleRegular />}>Invite your first person</Button></Card>;
  const activeReferralCount = data.referrals.filter((referral) => referral.status === 'Active').length;
  return <div className="page-stack"><section className="hero-panel hero-panel--compact"><Text className="hero-eyebrow">Referral circle</Text><Title1>Grow together, earn together.</Title1><Text className="hero-subtitle">Review contributions and commissions recorded for your referrals.</Text><Button appearance="primary" icon={<ArrowRightRegular />}>Send an invite</Button></section><section><div className="section-heading"><Title2>Referral activity</Title2><Text className="muted">{activeReferralCount} active {activeReferralCount === 1 ? 'referral' : 'referrals'}</Text></div><Card className="table-card"><Table aria-label="Referral activity"><TableHeader><TableRow><TableHeaderCell>Person</TableHeaderCell><TableHeaderCell>Joined</TableHeaderCell><TableHeaderCell>Contribution</TableHeaderCell><TableHeaderCell>Commission</TableHeaderCell><TableHeaderCell>Status</TableHeaderCell></TableRow></TableHeader><TableBody>{data.referrals.map((referral) => <TableRow key={referral.person}><TableCell><Text weight="semibold">{referral.person}</Text></TableCell><TableCell>{referral.joined}</TableCell><TableCell>{referral.contribution}</TableCell><TableCell>{referral.commission}</TableCell><TableCell><Badge color={referral.status === 'Active' ? 'success' : 'warning'}>{referral.status}</Badge></TableCell></TableRow>)}</TableBody></Table></Card></section></div>;
}
